# Generated by Django 4.2.2 on 2023-06-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("file", models.FileField(null=True, upload_to="")),
                (
                    "ref",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("url", models.URLField()),
                ("name", models.TextField(blank=True, null=True)),
                ("artistDisplayName", models.TextField(blank=True, null=True)),
                ("artistDisplayBio", models.TextField(blank=True, null=True)),
                ("artistNationality", models.TextField(blank=True, null=True)),
                ("country", models.TextField(blank=True, null=True)),
                ("region", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "metmuse.images",
            },
        ),
    ]
