# Generated by Django 4.2.2 on 2023-06-25 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("file", models.FileField(null=True, upload_to="")),
                (
                    "fetchable_image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="scheduling.fetchableimages",
                    ),
                ),
                ("url", models.URLField()),
                ("name", models.TextField(blank=True, null=True)),
                ("artistDisplayName", models.TextField(blank=True, null=True)),
                ("artistDisplayBio", models.TextField(blank=True, null=True)),
                ("artistNationality", models.TextField(blank=True, null=True)),
                ("country", models.TextField(blank=True, null=True)),
                ("region", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "metmuse.images",
            },
        ),
    ]
