version: "3.2"

services:

  backend-api:
    build: ../metmuse/backend
    container_name: metmuse-backend
    network_mode: 'host'
    volumes:
      - static_volume:/code/static
    environment:
      - SECRET_KEY=${SECRET_KEY:-mysupersecretkey123ShouldNeverDefault}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-mySuperSecRetrEd1sp@ssword}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-default-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-defaultadminpassword}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-defaultAdmin@cannotexist.doesnotexist}

  rq-worker:
    build: ../metmuse/backend
    container_name: rq-worker
    entrypoint: /bin/sh -c 'python3 /code/manage.py rqworker image-finder --with-scheduler'
    volumes:
      - media_media:/code/media
    environment:
      - SECRET_KEY=${SECRET_KEY:-mysupersecretkey123ShouldNeverDefault}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-mySuperSecRetrEd1sp@ssword}
      - REDIS_HOST=127.0.0.1
    depends_on:
      redis:
        condition: service_healthy

  rq-scheduler:
    build: ../metmuse/backend
    container_name: rq-scheduler
    entrypoint: /bin/sh -c 'python3 /code/manage.py rqscheduler --queue image-finder'
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SECRET_KEY=${SECRET_KEY:-mysupersecretkey123ShouldNeverDefault}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-mySuperSecRetrEd1sp@ssword}
      - REDIS_HOST=127.0.0.1
  
  renderer:
    build: renderer
    container_name: renderer
    volumes:
      - media_media:/src/media
      - static_volume:/src/static
    ports:
      - "127.0.0.1:80:80"
    networks:
      - mmr

  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD:-mySuperSecRetrEd1sp@ssword}
    networks:
      - mmr
    ports:
     - "127.0.0.1:6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli 127.0.0.1:6379 ping" ]
      interval: 20s
      timeout: 5s
      retries: 5
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  metmuse:
    build: ../metmuse
    container_name: metmuse-frontend
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - mmr


networks:
  mmr:
volumes:
  static_volume:
  media_media: