version: "3.2"

services:

  backend:
    build: ../metmuse/backend
    container_name: metmuse-backend
    network_mode: 'host'
    environment:
      - SECRET_KEY=${SECRET_KEY:-mysupersecretkey123WillNeverDefault}
  
  metmuse:
    build: ../metmuse
    container_name: metmuse-frontend
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - mmr


networks:
  mmr:
