# Generated by Django 4.2.2 on 2023-06-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FetchableImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.IntegerField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "This image is busy being fetched"),
                            (2, "There was an error while fetching this image"),
                            (3, "This image was fetched correctly"),
                            (4, "This image still needs to be fetched"),
                        ],
                        default=4,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fetchable Images",
                "db_table": "metmuse.fetchable_images",
            },
        ),
        migrations.CreateModel(
            name="SchedulingError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("retries", models.IntegerField(default=0)),
                ("request_response", models.JSONField(blank=True)),
                (
                    "fetchable_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduling.fetchableimage",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Scheduling Errors",
                "db_table": "metmuse.scheduling_errror",
            },
        ),
    ]
